FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PORT=7860
ENV NEXORA_PROVIDER=auto
ENV NEXORA_OLLAMA_MODE=fallback
ENV NEXORA_IMAGE_PROVIDER=pollinations
ENV NEXORA_HEALTH_DEEP=false
ENV NEXORA_CACHE_FRONTEND_HTML=true
ENV NEXORA_PERFORMANCE_LEVEL=balanced
ENV NEXORA_LOCAL_WRITING_FAST=false
ENV NEXORA_MAX_TOKENS=1600
ENV POLLINATIONS_TIMEOUT=18
ENV POLLINATIONS_PRIMARY_TIMEOUT=14
ENV POLLINATIONS_BACKUP_TIMEOUT=8
ENV POLLINATIONS_ATTEMPTS=1

WORKDIR /app

COPY backend/requirements.txt /app/backend/requirements.txt
RUN pip install --no-cache-dir -r /app/backend/requirements.txt

COPY backend /app/backend
COPY frontend /app/frontend

WORKDIR /app/backend

EXPOSE 7860

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port ${PORT:-7860}"]
